### ISSUE TITLE
cats with changed names retaining previous suffixes

### ISSUE THREAD

**Issue by shrimpsicle** [Thlumyn/clangen#102]
something ive noticed is if you change the name of a kit/apprentice before they finish their training (ex Icepaw -> Cloudpaw), when the cat finishes their training instead of receiving a proper suffix they will stay as whatever the changed name was (ex Cloudpaw doesn't become Cloudtail, stays as Cloudpaw).

**Comment by sedgestripe** [comment]
solved in #114 by @rmalusa72!
