### ISSUE TITLE
[development] Error loading cats

### ISSUE THREAD

**Issue by mooijtech** [Thlumyn/clangen#11]
Hello,

I am getting the following exception when loading (after having saved):
`IndexError: list index out of range`
https://github.com/Thlumyn/clangen/blob/e742aa312a31b67facdd717b31759161a2485271/scripts/cats.py#L1008

I believe this should be `experiencelevels[math.floor(int(the_cat.experience) / (len(experiencelevels) +1))]`

Edit: Note that I am using the development branch, as the mentor saving bug is not merged to the main branch yet.

Kind regards,
Marten Mooij

**Comment by mooijtech** [comment]
Instead of hardcoding everything how about something like this:
```python
import csv

# Cat
class Student:
    def __init__(self, student_id, first_name, last_name, mentor_students=None):
        self.student_id = student_id
        self.first_name = first_name
        self.last_name = last_name
        self.mentor_students = mentor_students

    def __repr__(self):
        return f"Student({self.student_id!r}, {self.first_name!r}, {self.last_name!r}, {self.mentor_students!r})"

    def __iter__(self):
        return iter([self.student_id, self.first_name, self.last_name, self.mentor_students])

# all_cats
my_students = [
    Student(1048, "John", "Adams"),
    Student(2517, "Karen", "Goodman"),
    Student(3131, "Anna", "Karenina", Student(1337, "Marten", "Mooij")),
]

# Write
with open("students.csv", "w") as stream:
    stream.write("# User hint of column definitions (when reading first line is skipped): student_id, first_name, last_name, mentor_students\n")

    writer = csv.writer(stream)
    writer.writerows(my_students)

print("Wrote students...")
print("Loading students...")

# Load
with open("students.csv") as stream:
    stream = csv.reader(stream)
    next(stream) # Skip header comment

    for row in stream:
        student = Student(*row)
        print("Got student from loaded CSV: " + student.first_name)
```

**Comment by Thlumyn** [comment]
Thanks, 

This is being worked on, with some comments here: https://github.com/Thlumyn/clangen/commit/fe7bf62f9b0fae7614a52686d4dee9253d84d9ac

**Comment by sedgestripe** [comment]
> Instead of hardcoding everything how about something like this:
> 
> ```python
> import csv
> 
> # Cat
> class Student:
>     def __init__(self, student_id, first_name, last_name, mentor_students=None):
>         self.student_id = student_id
>         self.first_name = first_name
>         self.last_name = last_name
>         self.mentor_students = mentor_students
> 
>     def __repr__(self):
>         return f"Student({self.student_id!r}, {self.first_name!r}, {self.last_name!r}, {self.mentor_students!r})"
> 
>     def __iter__(self):
>         return iter([self.student_id, self.first_name, self.last_name, self.mentor_students])
> 
> # all_cats
> my_students = [
>     Student(1048, "John", "Adams"),
>     Student(2517, "Karen", "Goodman"),
>     Student(3131, "Anna", "Karenina", Student(1337, "Marten", "Mooij")),
> ]
> 
> # Write
> with open("students.csv", "w") as stream:
>     stream.write("# User hint of column definitions (when reading first line is skipped): student_id, first_name, last_name, mentor_students\n")
> 
>     writer = csv.writer(stream)
>     writer.writerows(my_students)
> 
> print("Wrote students...")
> print("Loading students...")
> 
> # Load
> with open("students.csv") as stream:
>     stream = csv.reader(stream)
>     next(stream) # Skip header comment
> 
>     for row in stream:
>         student = Student(*row)
>         print("Got student from loaded CSV: " + student.first_name)
> ```

I've changed the exp levels back to what it was originally now and am working on rebalancing.

I wish the code base was more organized to have a cat.py class instead of saving all of the cats everywhere randomly and having everything hardcoded :(
But since this is a fan edit I think a lot of the code was already there and it'd take a lot of time to change it.

**Comment by mooijtech** [comment]
No worries, your work is much appreciated :)


________________________________
