### ISSUE TITLE
"Clangen" can't be opened on Mac Monterey

### ISSUE THREAD

**Issue by jeremiah** [Thlumyn/clangen#151]
I'm trying to run "Clangen" on an M1 Mac Monterey. When I download the Aug. 10 Mac image of Clangen I received a pop up saying "Clangen" cannot be opened because Apple cannot check it for malicious software. This software needs to be updated, contact the developer for more information."

I imagine they want to vet the code and ask that you release it via their App store, but I'm not sure. I thought I would report this to you. 

I note that clangen has issues where people note that they've got it running on Linux, I might give that a try.

**Comment by TheBlackfurGuy** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Hope this helps. Please get back to me so  I can close this issue.

**Comment by jeremiah** [comment]
Thanks, will test.

**Comment by Ryos00** [comment]
Assuming this issue was resolved. If not, resubmit.
