### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by leonoctem** [Thlumyn/clangen#156]
a couple of suggestions that i think would improve the game a tiny bit!

1) currently when you select a cat for a patrol, you can't remove it or check it's details. I'd suggest the ability to click on cats already in a patrol, and have them come up as the cats that can be selected do, and instead of 'add to patrol' on them, have 'remove from patrol'

2) have 'fomerly a loner/kittypet' in a separate field to the field where 'great hunter' etc is displayed, and give loners/kittypets skills like the clan born cats. for clan born cats the field with 'fomerly a loner/kittypet' could have something like 'clan born'.

**Comment by anjubatus** [comment]
The profile screen is getting a bit full of text, I agree with separating the clan born/loners/kittypets from the skill part but I'm thinking it'd be even better if something like this could be done with a small image/symbol icon instead?

**Comment by leonoctem** [comment]
> The profile screen is getting a bit full of text, I agree with separating the clan born/loners/kittypets from the skill part but I'm thinking it'd be even better if something like this could be done with a small image/symbol icon instead?

that's a good option too! and if a symbol is used it should have a mention of what the symbols mean in the settings/info area

**Comment by Locustfang339** [comment]
what if we could create our own clans' symbols?
