### ISSUE TITLE
Clan gen is broken?

### ISSUE THREAD

**Issue by BadPizza23** [Thlumyn/clangen#162]
Well, it's me again. Clan gen is just not working. Here is the WHOLE ERROR LIST D:

ModuleNotFoundError: No module named 'ujson'
cp_back.py, line 264
No specific suggestions for this error (yet).
Let Thonny developers know
Click on the feedback link at the bottom of this panel to let Thonny developers know about your problem. They may add support for such cases in future Thonny versions.
Search the web
Try performing a web search for
Python ModuleNotFoundError: No module named 'ujson'

Warnings
May help you find the cause of the error.
main.py
Line 3 : Unused path imported from os
It looks like the imported module or variable is not used.
Line 11 : Name "pygame" is not defined
Line 12 : Name "pygame" is not defined
Line 17 : Using open without explicitly specifying an encoding
It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/
Line 19 : Using open without explicitly specifying an encoding
It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/
Line 23 : Name "game" is not defined
Line 25 : Name "cat_class" is not defined
Line 26 : Name "clan_class" is not defined
Line 27 : Name "cat_class" is not defined
Line 29 : Name "game" is not defined
Line 30 : Name "game" is not defined
Line 34 : Name "game" is not defined
Line 34 : Name "load_map" is not defined
Line 36 : Name "game" is not defined
Line 38 : Name "game" is not defined
Line 38 : Name "load_map" is not defined
Line 43 : Using open without explicitly specifying an encoding
It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See https://peps.python.org/pep-0597/
Line 45 : Name "game" is not defined
Line 48 : Name "verdana" is not defined
Line 49 : Name "buttons" is not defined
Line 50 : Name "sprites" is not defined
Line 52 : Name "pygame" is not defined
Line 55 : Name "game" is not defined
Line 56 : Name "screen" is not defined
Line 58 : Name "screen" is not defined
Line 60 : Name "game" is not defined
Line 61 : Name "verdana" is not defined
Line 62 : Name "buttons" is not defined
Line 64 : Name "mouse" is not defined
Line 67 : Name "pygame" is not defined
Line 68 : Name "game" is not defined
Line 71 : Name "cat_class" is not defined
Line 71 : Name "game" is not defined
Line 72 : Name "game" is not defined
Line 73 : Name "cat_class" is not defined
Line 74 : Name "cat_class" is not defined
Line 76 : Name "cat_class" is not defined
Line 77 : Name "cat_class" is not defined
Line 78 : Name "cat_class" is not defined
Line 79 : Name "game" is not defined
Line 79 : Name "cat_class" is not defined
Line 81 : Name "cat_class" is not defined
Line 82 : Name "cat_class" is not defined
Line 83 : Name "cat_class" is not defined
Line 84 : Name "cat_class" is not defined
Line 85 : Name "game" is not defined
Line 85 : Name "cat_class" is not defined
Line 87 : Name "cat_class" is not defined
Line 92 : Name "pygame" is not defined
Line 93 : Name "pygame" is not defined
Line 94 : Name "game" is not defined
Line 95 : Name "pygame" is not defined
Line 96 : Name "game" is not defined
Line 97 : Name "pygame" is not defined
Line 98 : Name "game" is not defined
Line 99 : Name "pygame" is not defined
Line 100 : Name "game" is not defined
Line 101 : Name "game" is not defined
Line 102 : Name "game" is not defined
Line 103 : Name "pygame" is not defined
Line 107 : Name "game" is not defined
Line 108 : Name "game" is not defined
Line 109 : Name "game" is not defined
Line 110 : Name "pygame" is not defined
Line 111 : Name "game" is not defined
Line 114 : Name "game" is not defined
Line 115 : Name "game" is not defined
Line 117 : Name "game" is not defined
Line 118 : Name "pygame" is not defined
Line 119 : Name "pygame" is not defined
Line 119 : Name "game" is not defined
Line 120 : Name "game" is not defined
Line 121 : Name "game" is not defined
Line 122 : Name "pygame" is not defined
Line 123 : Name "game" is not defined
Line 124 : Name "game" is not defined
Line 125 : Name "game" is not defined
Line 126 : Name "pygame" is not defined
Line 127 : Name "game" is not defined
Line 128 : Name "game" is not defined
Line 129 : Name "game" is not defined
Line 131 : Name "game" is not defined
Line 132 : Name "game" is not defined
Line 133 : Name "game" is not defined
Line 135 : Name "game" is not defined
Line 136 : Name "game" is not defined
Line 138 : Name "game" is not defined
Line 139 : Name "pygame" is not defined
Line 140 : Name "pygame" is not defined
Line 140 : Name "game" is not defined
Line 141 : Name "game" is not defined
Line 142 : Name "game" is not defined
Line 143 : Name "pygame" is not defined
Line 144 : Name "game" is not defined
Line 145 : Name "game" is not defined
Line 146 : Name "game" is not defined
Line 147 : Name "pygame" is not defined
Line 148 : Name "game" is not defined
Line 149 : Name "game" is not defined
Line 150 : Name "game" is not defined
Line 152 : Name "game" is not defined
Line 153 : Name "game" is not defined
Line 154 : Name "game" is not defined
Line 155 : Name "game" is not defined
Line 156 : Need type annotation for "random_options" (hint: "random_options: List[<type>] = ...")
Line 157 : Name "pygame" is not defined
Line 158 : Name "pygame" is not defined
Line 160 : Name "game" is not defined
Line 162 : Name "game" is not defined
Line 163 : Name "game" is not defined
Line 164 : Name "game" is not defined
Line 165 : Name "pygame" is not defined
Line 168 : Name "game" is not defined
Line 170 : Name "game" is not defined
Line 171 : Name "pygame" is not defined
Line 172 : Name "game" is not defined
Line 174 : Name "game" is not defined
Line 175 : Name "pygame" is not defined
Line 178 : Name "game" is not defined
Line 180 : Name "game" is not defined
Line 181 : Name "pygame" is not defined
Line 182 : Name "game" is not defined
Line 184 : Name "game" is not defined
Line 186 : Name "pygame" is not defined
Line 189 : Name "game" is not defined
Line 191 : Name "game" is not defined
Line 192 : Name "pygame" is not defined
Line 193 : Name "game" is not defined
Line 196 : Name "pygame" is not defined
Line 198 : Name "pygame" is not defined
Line 199 : Name "pygame" is not defined
Line 203 : Name "pygame" is not defined
Line 204 : Name "game" is not defined
Line 206 : Name "pygame" is not defined
Line 207 : Name "game" is not defined
Line 208 : Name "pygame" is not defined
Line 209 : Name "pygame" is not defined
Line 210 : Name "game" is not defined
Line 211 : Name "pygame" is not defined
Line 212 : Name "game" is not defined
Line 213 : Name "pygame" is not defined
Line 214 : Name "game" is not defined
Line 215 : Name "pygame" is not defined
Line 216 : Name "game" is not defined
Line 217 : Name "pygame" is not defined
Line 218 : Name "game" is not defined
Line 219 : Name "pygame" is not defined
Line 220 : Name "game" is not defined
Line 221 : Name "pygame" is not defined
Line 222 : Name "game" is not defined
Line 223 : Name "pygame" is not defined
Line 224 : Name "game" is not defined
Line 225 : Name "pygame" is not defined
Line 226 : Name "game" is not defined
Line 227 : Name "pygame" is not defined
Line 228 : Name "game" is not defined
Line 229 : Name "pygame" is not defined
Line 230 : Name "game" is not defined
Line 231 : Name "pygame" is not defined
Line 232 : Name "game" is not defined
Line 233 : Name "pygame" is not defined
Line 234 : Name "game" is not defined
Line 235 : Name "pygame" is not defined
Line 236 : Name "game" is not defined
Line 237 : Name "pygame" is not defined
Line 238 : Name "game" is not defined
Line 239 : Name "pygame" is not defined
Line 240 : Name "game" is not defined
Line 241 : Name "pygame" is not defined
Line 242 : Name "game" is not defined
Line 243 : Name "pygame" is not defined
Line 244 : Name "game" is not defined
Line 245 : Name "pygame" is not defined
Line 246 : Name "game" is not defined
Line 247 : Name "pygame" is not defined
Line 248 : Name "game" is not defined
Line 249 : Name "pygame" is not defined
Line 250 : Name "game" is not defined
Line 251 : Name "pygame" is not defined
Line 252 : Name "game" is not defined
Line 253 : Name "pygame" is not defined
Line 254 : Name "game" is not defined
Line 255 : Name "pygame" is not defined
Line 256 : Name "game" is not defined
Line 259 : Name "game" is not defined
Line 262 : Name "game" is not defined
Line 263 : Name "game" is not defined
Line 264 : Name "screens" is not defined
Line 264 : Name "game" is not defined
Line 265 : Name "game" is not defined
Line 269 : Name "pygame" is not defined

>>> %Run main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\NAME\Downloads\clangen-development\clangen-development\main.py", line 8, in <module>
    from scripts.screens import *
  File "C:\Users\NAME\Downloads\clangen-development\clangen-development\scripts\screens.py", line 3, in <module>
    from .clan import *
  File "C:\Users\NAME\Downloads\clangen-development\clangen-development\scripts\clan.py", line 1, in <module>
    from .cats import *
  File "C:\Users\NAME\Downloads\clangen-development\clangen-development\scripts\cats.py", line 10, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
>>> 

Anyhelp?

**Comment by Locustfang339** [comment]
Clangen won't work for me either. My thoughts are maybe it added a virus to the computer (I'm on a school chromebook) or maybe we did something we weren't supposed to. I was about to make a new clan but it froze when i tried to make it the beach camp. this was today.

**Comment by Ickaboggle** [comment]
Yes, It just shows the blank, gray screen for me. Its been happening for a couple of months now, maybe 2-3. Please try to fix it bc this is the only thing that'll work for me :,D

**Comment by Shadyfur-Shadowedheart** [comment]
It seems as if the game hasn't properly installed on the device. The device can't handle the game which the memory cannot suffice. The game breaks. I'd suggest getting a less updated version or some device with better memory.

Hope this helps
