### ISSUE TITLE
Suggestion/request - ability to remove accessories ingame

### ISSUE THREAD

**Issue by Snowstar38** [Thlumyn/clangen#185]
I really love the new accessories! But every once in a while, I roll one that might (to me) clash with personality/fur color. Could a button be added to the menu to give the option to remove an accessory for a specific cat, so I don't have to edit the save file manually?

(sorry if this is the wrong place for a request; I didn't see another place to put this!)

**Comment by sedgestripe** [comment]
added in https://github.com/Thlumyn/clangen/commit/0ec4cf3d150e1aff7e6817f29feee46323c1545d !
