### ISSUE TITLE
Birth defects and more acquired disabilities 

### ISSUE THREAD

**Issue by SP20YT** [Thlumyn/clangen#191]
Heyo, I would like to play a Clangen with the possibility that I could get a cat with a genetic disability, and also pls add more disabilities.
Some examples that I'm talking about are:
Lack of lower/upper jaw ( Both genetic and acquired )
Autism ( Genetic )
All other disability ( genetic and acquired )
Etc.

**Comment by BadPizza23** [comment]
That would be so cool!!!!

**Comment by Aprilx111** [comment]
That would be amazimg

**Comment by Ryos00** [comment]
Permanent conditions and disabilities have been implemented.
