### ISSUE TITLE
Are you open to changing the saved format from CSV to json?

### ISSUE THREAD

**Issue by djotaku** [Thlumyn/clangen#21]
If you are, do you prefer PRs into main or development?

**Comment by Thlumyn** [comment]
Yeah, we are, I think @ikethefifth and some of us were discussing it, we were going to change it after the next update but if you want to get started on it please be my guest, I prefer PRs into development

**Comment by djotaku** [comment]
OK, cool. I'll give it a shot over the next few days.

**Comment by djotaku** [comment]
```python
    def load_cats(self):
        if game.switches['clan_list'][0].strip() == '':
            cat_data = {}
        else:
            if os.path.exists('saves/' + game.switches['clan_list'][0] + 'cats.csv'):
                with open('saves/' + game.switches['clan_list'][0] + 'cats.json', 'r') as read_file:
                    file = read_file.read()
                    cat_data = json.loads(file)
            else:
                with open('saves/' + game.switches['clan_list'][0] + 'cats.txt', 'r') as read_file:
                    cat_data = read_file.read()

```

Working on this now. (Ignoring the json lines I added) I'm curious why you're either opening the CSV or a text file? Seems you should either have one type of data or the other, not two wildly different types of files

**Comment by Thlumyn** [comment]
Some older versions of the game use a txt file instead of a csv file; it saves it as a csv file but I added it loading in a txt file so players could bring in their saves from older versions to the newer versions

**Comment by Thlumyn** [comment]
We could probably remove the txt file part now... pretty much everybody is on csv at this point

**Comment by djotaku** [comment]
OK, I'll continue based on that, then.
