### ISSUE TITLE
Linux release?

### ISSUE THREAD

**Issue by joshuaalm** [Thlumyn/clangen#29]
I just tested this in WSL Debian on Windows 11 running Python 3.9.2.  It ran perfectly and I was able to use the menu, create a clan, play for a number of moons.  What steps are needed to make this available as a packaged Linux download?

The steps I took to get it to run:
1. Install WSL Debian from Windows Store (Should work on Debian or Raspbian)
2. Install Python 3.x from apt: `sudo apt install python3`
3. Install pygame: `pip install pygame`
4. Run main.py via Python: `python3 main.py`

This could make the game available to e.g. those running Chromebooks as well.

**Comment by Bubalo1234** [comment]
hello so im not that tech-savvy but from my knowledge of python, you just need to find someone with a linux computer and ask them to compile it with some python thing but again m not that sure :/

**Comment by joshuaalm** [comment]
Yeah, I get that. Not sure the best way to distribute for Linux these days. I can make an apt/rpm but I figured it would be easier for users to distribute it as a snap. Again, thinking of Chromebook users in particular.

**Comment by Bubalo1234** [comment]
yeah. I don't have a linux computer so I kinda can't help ya there...

**Comment by StormLight14** [comment]
> hello so im not that tech-savvy but from my knowledge of python, you just need to find someone with a linux computer and ask them to compile it with some python thing but again m not that sure :/

Yeah I used Pyinstaller in the past and made a Linux build, but never was accepted as an official one

**Comment by StormLight14** [comment]
> Yeah, I get that. Not sure the best way to distribute for Linux these days. I can make an apt/rpm but I figured it would be easier for users to distribute it as a snap. Again, thinking of Chromebook users in particular.

Also God no about snap

**Comment by Bubalo1234** [comment]
snap is 100% ok and I dont have a Chromebook but cant they just compile it themselves?

**Comment by StormLight14** [comment]
snap is not good, idk why people defend it so much

**Comment by Ryos00** [comment]
Linux build has been added
