### ISSUE TITLE
yml file not working

### ISSUE THREAD

**Issue by Bubalo1234** [Thlumyn/clangen#39]
I was porting it to repl cuz I have dumb computer and this was an error it kept giving me about the yaml:

jobs:
     ^
SyntaxError: invalid syntax

I know how yaml works (mostly) but I don't see anything wrong. please help me so I can play this game!!!

This is the code I have bcz I managed to fix some errors (hopefully nothing broke)

name: "Clangen CI/CD"
on: push

jobs:
  build-macos:
    runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2
    - run: "pip3 install pygame pyinstaller pillow"
    - run: "pyinstaller --onefile -w -n Clangen -i resources/icon.png main.py"
    - run: "mkdir -p dist/Clangen.app/Contents/Resources/sprites"
    - run: "mkdir dist/Clangen.app/Contents/Resources/saves"
    - run: "mkdir dist/Clangen.app/Contents/Resources/resources"
    - run: "cp sprites/* dist/Clangen.app/Contents/Resources/sprites"
    - run: "cp resources/* dist/Clangen.app/Contents/Resources/resources"
    - run: "rm dist/Clangen"
    - run: "codesign --force --sign - dist/Clangen.app"
    - run: "ln -s /Applications/ dist/"
    - run: "hdiutil create Clangen.dmg -ov -volname 'Clangen' -fs HFS+ -format UDZO -srcfolder './dist/'"
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: Clangen.dmg

**Comment by BeaconBrigade** [comment]
Looking at the `.replit` file in your repl, it looks like you're trying to run yml file using a python interpreter. This is the source of all the errors you're getting. You can't run yml using a python interpreter since they're different languages.  Also, that yml file is for packaging the app as a dmg file for macos. Replit uses linux to run the your projects so this yml doesn't really help you to run the project. You probably should be able to run the project in replit by changing the entrypoint in the `.replit` back to `main.py`. Let me know if you have any issues.

**Comment by Bubalo1234** [comment]
oh ty :) btw im kinda new to this stuff I usually use unity actually.. what is the "entry point"? sry im just a noob :P

**Comment by Bubalo1234** [comment]
ah so I tinkered around for a bit and I made the entry point the main.py but now It gives me a ton of errors like 

File "main.py", line 2, in <module>
  from scripts.screens import *
File "/home/runner/clangen/scripts/screens.py", line 1, in <module>
    from .clan import *
  File "/home/runner/clangen/scripts/clan.py", line 1, in <module>
    from .cats import *
  File "/home/runner/clangen/scripts/cats.py", line 3, in <module>
    from .sprites import *
  File "/home/runner/clangen/scripts/sprites.py", line 2, in <module>
what do I do???

**Comment by Bubalo1234** [comment]
hm. I did that this is a screenshot. what else do I do? I changed the way the "import" lines bt changing it from, say,  ".screens" to "scripts.screens". that fixed a lot of bugs but did I break anything

<img width="198" alt="Screen Shot 2022-08-30 at 12 16 12 PM" src="https://user-images.githubusercontent.com/80659275/187524267-00ae28ff-4480-4267-bd6e-6ba30d8cedd0.png">

**Comment by Bubalo1234** [comment]
OMG I FOUND THE PROBLEM!!! I needed to use pygame. IT WORKS NOW!! TY u really helped my fix.

**Comment by Bubalo1234** [comment]
you know, while trying to fix this I learned a lot about python. I'm knowledgable with it just I have 0 idea how to use replit for python (I use it for java more) :P
u know, I want to be an artist for the game now XD

**Comment by BeaconBrigade** [comment]
Glad I could help, you always learn the most when you run into annoying issues that you have to hurdle to continue.

**Comment by Bubalo1234** [comment]
:) see ya! ty
