### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by Clumxy** [Thlumyn/clangen#42]
Hello! I have a suggestion for your fan edit of ClanGen! I suggest adding a setting that makes your save Files interact with one an other. If turned off, that will make it so clan names are generated! but if its turned on, that means your other saves can interact with your main Clan.  Also, you may control whatever relationship an Clan has with an other. I also think territory maps should be added in.
Clan Interactions Example:
![Screenshot 2022-08-27 032237](https://user-images.githubusercontent.com/88956931/187021993-fe675563-2fb1-4bb1-8b16-e77a8a938bf7.png)
Territory Map Example:
![Charigny 2022-08-23-00-41](https://user-images.githubusercontent.com/88956931/187022122-0d1fdcdf-97ed-4a0e-8c30-50fb59cd9ff6.png)

What do you think?

Pros:
More freedom between what you want.
More drama to your already saved clans
Beautifully generated maps.

Cons: 
Clan maps might bug and might add in lag if too realistic.

**Comment by Clumxy** [comment]
oop that was ment for development version

**Comment by Bubalo1234** [comment]
hello!!! im not actually part of the team but I'll try this on my free time
u know I kinda wanna be an artist XD
I might be able to do this with Merlin noise, I'll try to use a radial gradient to get this to work. I would love this tbh! im not that good at programming with a team but I could help with the art :)

**Comment by Aprilx111** [comment]
THIS IS AMAZING> YES>
