### ISSUE TITLE
Remember how a cat died

### ISSUE THREAD

**Issue by hen** [Thlumyn/clangen#68]
(We're playing on the development branch)

On the StarClan, it would be great if it remembered how the cat died.

**Comment by Bubalo1234** [comment]
that'd be nice. ill work on it......... hopefully. Im kinda busy tho

**Comment by rmalusa72** [comment]
Since this would require saving more info in the cat object, I wonder if it would be easier to wait until after the cat save files are switched from CSV to JSON.

**Comment by Ryos00** [comment]
This has been fully implemented with the history tab
