### ISSUE TITLE
History

### ISSUE THREAD

**Issue by hen** [Thlumyn/clangen#70]
[Playing on the development branch]

Would be great to have a history button, that lets you see a scrollable list of every event your clan has ever had; with the Clan Age and Current season included.

Allowing the player to add their own notes here would be great, letting them build their story around the events.

**Comment by Bubalo1234** [comment]
oooo that would be awesome! ill get to work

**Comment by rmalusa72** [comment]
I'm also working on a version of this -- it won't be in the next release but when I have a version working I can let you know if you want to test it! :)

**Comment by Ryos00** [comment]
History is now implemented
