### ISSUE TITLE
Kits spirits don't appear and causes an unhandled exception in script.

### ISSUE THREAD

**Issue by LordShaxxsWife** [Thlumyn/clangen#9]
Failed to execute script 'main' due to unhandled exception: No file 'sprites/lineart.png' found in working directory 'C:\WINDOWS\system32'.

What had happened in game was the event text told me one of my female cats died then underneath it I read the text that the same female cat had kits, so I clicked on the mother's sprite in Starclan and saw that the three kits didn't have sprites, this caused the unhandled exception in script to pop up. I can't access the save anymore as it just pops up with the unhandled exception.

**Comment by Thlumyn** [comment]
Fixed here: https://github.com/Thlumyn/clangen/commit/b19bc55a82723abc2edbb79ef371d558216ad014

The cat sprites were only generating when viewing the clan page; this regenerates them when viewing other pages that might be looked at before the clan page is viewed (list, profile, starclan, family page)
